'use strict';

function stub(name) {
  return async function (...args) {
    console.log(`[openclaw-ext] ${name}(${args.map(a => JSON.stringify(a)).join(', ')})`);
    return { result: null, command: name, args };
  };
}

module.exports = {
  timeInMarket: stub('timeInMarket'),
  timeSinceEvent: stub('timeSinceEvent'),
  schedule: stub('schedule'),
  waitUntil: stub('waitUntil'),
  marketScan: stub('marketScan'),
  portfolioBuild: stub('portfolioBuild'),
  portfolioRebalance: stub('portfolioRebalance'),
  econData: stub('econData'),
  econIndicator: stub('econIndicator'),
  estimate: stub('estimate'),
  fetchHistorical: stub('fetchHistorical'),
  fetchMembers: stub('fetchMembers'),
  groupMembers: stub('groupMembers'),
  fiscalFlow: stub('fiscalFlow'),
  electionImpact: stub('electionImpact'),
  currencyCarry: stub('currencyCarry'),
  policySentiment: stub('policySentiment'),
  sanctionImpact: stub('sanctionImpact'),
  votePredict: stub('votePredict'),
  mathModel: stub('mathModel'),
  riskModel: stub('riskModel'),
  monteCarlo: stub('monteCarlo'),
  taskSchedule: stub('taskSchedule'),
  fileParse: stub('fileParse'),
  weatherImpact: stub('weatherImpact'),
  strategyEntry: stub('strategyEntry'),
  strategyExit: stub('strategyExit'),
  strategyClose: stub('strategyClose'),
  inputInt: stub('inputInt'),
  inputFloat: stub('inputFloat'),
  inputBool: stub('inputBool'),
  inputSymbol: stub('inputSymbol'),
  timeframePeriod: stub('timeframePeriod'),
  timeframeIsDaily: stub('timeframeIsDaily'),
  arrayNew: stub('arrayNew'),
  arrayPush: stub('arrayPush'),
  matrixNew: stub('matrixNew'),
  matrixSet: stub('matrixSet'),
  prtAverage: stub('prtAverage'),
  prtRsi: stub('prtRsi'),
  prtMacd: stub('prtMacd'),
  prtBollinger: stub('prtBollinger'),
  prtStochastic: stub('prtStochastic'),
  prtAtr: stub('prtAtr'),
  prtCci: stub('prtCci'),
  prtAdx: stub('prtAdx'),
  prtDonchian: stub('prtDonchian'),
  prtIchimoku: stub('prtIchimoku'),
  prtKeltnerchannel: stub('prtKeltnerchannel'),
  prtParabolicsar: stub('prtParabolicsar'),
  prtSupertrend: stub('prtSupertrend'),
  prtVolumebyprice: stub('prtVolumebyprice'),
  prtFibonacci: stub('prtFibonacci'),
  prtPivotpoint: stub('prtPivotpoint'),
  prtDemark: stub('prtDemark'),
  prtWilliams: stub('prtWilliams'),
  prtUltosc: stub('prtUltosc'),
  prtChaikin: stub('prtChaikin'),
  prtOnbalancevolume: stub('prtOnbalancevolume'),
  prtVwap: stub('prtVwap'),
  prtCum: stub('prtCum'),
  prtHighest: stub('prtHighest'),
  prtLowest: stub('prtLowest'),
  prtSum: stub('prtSum'),
  prtStd: stub('prtStd'),
  prtCorrelation: stub('prtCorrelation'),
  prtRegression: stub('prtRegression'),
  prtSummation: stub('prtSummation'),
  prtHistogram: stub('prtHistogram'),
  prtCross: stub('prtCross'),
  prtBarssince: stub('prtBarssince'),
  prtBarindex: stub('prtBarindex'),
  prtDate: stub('prtDate'),
  prtTime: stub('prtTime'),
  prtDefparam: stub('prtDefparam'),
  prtReturn: stub('prtReturn'),
  prtDrawline: stub('prtDrawline'),
  prtDrawarrow: stub('prtDrawarrow'),
  prtTimeframe: stub('prtTimeframe'),
};
